### ISSUE TITLE
findarg from findfn

### ISSUE THREAD

**Issue by borkdude** [borkdude/re-find.web#28]
https://github.com/Raynes/lein-findfn

**Comment by borkdude** [comment]
Not sure how useful this is, since you can deduce from `(map % [1 2 3]) => [2 3 4])` that you want to find % such that `(% 1) => 2`, which is `inc`.

**Comment by jeshan** [comment]
Thanks, I should have paid more attention to this:
![image](https://user-images.githubusercontent.com/1020565/62975063-90dfca00-be2a-11e9-9128-7f54cc3d5139.png)
![image](https://user-images.githubusercontent.com/1020565/62975090-a48b3080-be2a-11e9-93ac-3f7154eaa807.png)
