### ISSUE TITLE
Doesn't find reverse function

### ISSUE THREAD

**Issue by jeshan** [borkdude/re-find.web#93]
I'm trying the following inputs in repl.it:

Args: `'(1 2 3)`
Returns: `'(3 2 1)`

or:
Args: `(list 1 2 3)`
Returns: `(list 3 2 1)`

I was expecting it to find the `reverse` function. Instead it may or may not find the `shuffle` function (since `shuffle` is not idempotent)

Example link:
https://re-find.it/?args=%27%281%202%203%29&ret=%27%283%202%201%29&more=true

It does not look like expected behaviour

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/re-find.web/commit/419111ad3ae7ccb7860f26caa3a0401c1cde8674

**Comment by borkdude** [comment]
Note to self and others: you can find a list of all available specs by executing this in the console:

```
cljs.core.clj__GT_js(cljs.spec.test.alpha.instrumentable_syms())
```

It's a bit cumbersome, but it might help explain why something isn't working.

**Comment by jeshan** [comment]
Thanks, I should have paid more attention to this:
![image](https://user-images.githubusercontent.com/1020565/62975063-90dfca00-be2a-11e9-9128-7f54cc3d5139.png)
![image](https://user-images.githubusercontent.com/1020565/62975090-a48b3080-be2a-11e9-93ac-3f7154eaa807.png)
